### ISSUE TITLE
Bug: INSTALL_FAILED_CONFLICTING_PROVIDER [1-2h]

### ISSUE THREAD

**Issue by literacyapp** [literacyapp-org/android_packages_apps_Trebuchet_Gradle#5]
APK installation fails:

```
$ adb install -r Trebuchet/build/outputs/apk/Trebuchet-debug.apk 
Failure [INSTALL_FAILED_CONFLICTING_PROVIDER]
```

**Comment by bojanvu23** [comment]
This has to be tested on real device, so here is apk:
https://drive.google.com/file/d/0B9fibiIaI_3ZLW14YUpoSjR6aDA/view?usp=sharing
If it's work, it will close https://github.com/literacyapp-org/android_packages_apps_Trebuchet_Gradle/issues/7
because there is problem with removing permission WRITE_SETTINGS, and in this app it's exist.

Please check this, after that I will commit changes.

And after that check #2, because all of them are related.

Note: before installing new apk, you have to go in app info and do 'uninstall for all users'.


Bojan

**Comment by jogrimst** [comment]
@bojanvu23 Instead of uploading an APK, can you add the code changes to GitHub? This way we can do code review, as well as fetching the latest version from your private GitHub fork. Then, if the code changes and functionality are okay, we can merge the pull request.

**Comment by bojanvu23** [comment]
@jogrimst

@jogrimst 
Hi I did it because only way to check this is chaining package of whole project, I used my moto x with cyanogenmode because still I'm finding to get...and I didn't want a lot changes/reverts on repository.

Anyway, I'm going to push changes. 
Note: For this I had to change package name of project, so there is change on every project file.

**Comment by bojanvu23** [comment]
This is fixed, closing ticket.
